---
key: impressum
---

== Reservierung und Buchung

. Die Reservierung des Afenthalts erfolgt ausschliesslich über die Webseite http://www.riodelamiel.eu, per
link:mailto:reservations@riodelamiel.eu[eMail] oder link:tel:+34958199061[telefonisch]. Eine Reservierung sollte immer unter Angabe eines gewünschten
Aufenthaltszeitraumes bzw. Seminars und einer Zimmerkategorie erfolgen.
. Nach Eingang der Reservierung wird diese von _Rio de la Miel_ per eMail bestätigt. Nach Erhalt der
Reservierungsbestätigung ist innerhalb von 5 Tagen eine Anzahlung von 25% des Gesamtpreises zu entrichten, so daß
ausreichend Zeit gegeben ist, um Flüge für die An- und Abreise zu buchen.
. Für einen Karmayogaaufenthalt reicht die schriftliche Bestätigung seitens _Rio de la Miel_ für die Verbindlichkeit aus.
. Wird innerhalb von 5 Arbeitstagen die Anzahlung nicht geleistet, verfällt die Reservierung und muss erneut getätigt
werden.
. Bei Ankunft sind die verbleibenden 75% des Reisepreises fällig.

=== Stornierungen

. Die Reise kann bis 4 Wochen vor Reiseantritt storniert werden. In diesem Fall verfällt die geleistete Anzahlung.
Ein Recht auf Rückerstattung besteht ausdrücklich nicht.
. Bei einer späteren Stornierung ist der volle Reisepreis zu entrichten. Wir empfehlen den Abschluss einer
Reiserücktrittsversicherung, um krankheitsbedingte Ausfälle abzudecken.
. Sofern ein Kurs auf Grund mangelnder Anmeldungen nicht durchgeführt werden kann, kann der Gast zwischen einer
kostenfreien Stornierung und einer Umwandlung in einen Yogaaufenthalt wählen. Im Falle der Umwandlung werden eventuell
zuviel gezahlte Kursgebühren zurück erstattet.

---

== Rechtliche Hinweise

=== Haftungsbeschränkung

Die Inhalte des Internetauftritts wurden mit größtmöglicher Sorgfalt und nach bestem Gewissen erstellt. Dennoch übernimmt
der Anbieter dieser Webseite keine Gewähr für die Aktualität, Vollständigkeit und Richtigkeit der bereitgestellten Seiten
und Inhalte.

Als Diensteanbieter ist der Anbieter dieser Webseite gemäß § 7 Abs. 1 TMG für eigene Inhalte und bereitgestellte
Informationen auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich; nach den §§ 8 bis 10 TMG jedoch nicht
verpflichtet, die übermittelten oder gespeicherten fremden Informationen zu überwachen. Eine Entfernung oder Sperrung
dieser Inhalte erfolgt umgehend ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung.
Eine Haftung ist erst ab dem Zeitpunkt der Kenntniserlangung möglich.

=== Externe Links

Die Webseite enthält sog. „externe Links“ (Verlinkungen) zu anderen Webseiten, auf deren Inhalt der Anbieter der
Webseite keinen Einfluss hat. Aus diesem Grund kann der Anbieter für diese Inhalte auch keine Gewähr übernehmen.
Für die Inhalte und Richtigkeit der bereitgestellten Informationen ist der jeweilige Anbieter der verlinkten Webseite
verantwortlich. Zum Zeitpunkt der Verlinkung waren keine Rechtsverstöße erkennbar. Bei Bekanntwerden einer solchen
Rechtsverletzung wird der Link umgehend entfernt.

=== Urheberrecht/Leistungsschutzrecht

Die auf dieser Webseite veröffentlichten Inhalte, Werke und bereitgestellten Informationen unterliegen dem deutschen
Urheberrecht und Leistungsschutzrecht. Jede Art der Vervielfältigung, Bearbeitung, Verbreitung, Einspeicherung und
jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedarf der vorherigen schriftlichen Zustimmung des
jeweiligen Rechteinhabers. Das unerlaubte Kopieren/Speichern der bereitgestellten Informationen auf diesen Webseiten
ist nicht gestattet und strafbar.

=== Datenschutz

Durch den Besuch des Internetauftritts können Informationen (Datum, Uhrzeit, aufgerufene Seite) über den Zugriff auf
dem Server gespeichert werden. Es werden keine personenbezogenenen (z. B. Name, Anschrift oder E-Mail-Adresse) Daten,
gespeichert.

Sofern personenbezogene Daten erhoben werden, erfolgt dies, sofern möglich, nur mit dem vorherigen Einverständnis des
Nutzers der Webseite. Eine Weitergabe der Daten an Dritte findet ohne ausdrückliche Zustimmung des Nutzers nicht statt.

Der Anbieter weist darauf hin, dass die Übertragung von Daten im Internet (z. B. per E-Mail) Sicherheitslücken aufweisen
und ein lückenloser Schutz der Daten vor dem Zugriff Dritter nicht gewährleistet werden kann. Der Anbieter übernimmt
keine Haftung für die durch solche Sicherheitslücken entstandenen Schäden.

Der Verwendung der Kontaktdaten durch Dritte zur gewerblichen Nutzung wird ausdrücklich widersprochen. Es sei denn,
der Anbieter hat zuvor seine schriftliche Einwilligung erteilt. Der Anbieter behält sich rechtliche Schritte für den
Fall der unverlangten Zusendung von Werbeinformationen, z.B. durch Spam-Mails, vor.

---

[cols="3"]
|===
|*Verantwortlich für den Inhalt*
|
|Godea Vida S.L.U.

|
|
|Plaza Cavana 5

|
|
|29780 Nerja

|
|
|Spanien

|*Geschäftsführer*
|
|Karin Gies

|*eMail*
|
|mailto:info@wayofquality.de

|*Telefon*
|
|+34 958 199 061

|*C.I.F.*
|
|B93426559

|*Ust.-Id.*
|
|ESB93426559
|===
