---
key: contact
layout: pageminimal
---
=== Sprecht uns an
Für Fragen rund um euren Aufenthalt und eure Seminare in Rio de la Miel wir Ihnen gerne per Telefon oder eMail zur Verfügung.

Wir helfen nach Kräften bei der Organisation der Anreise oder mit informationen über zusätzliche Angebote in der näheren Umgebung.
Zögert nicht, uns zu kontaktieren - wir freuen uns auf euch.

=== Veranstalter
WoQ - Way of Quality GmbH +
Stahlzwingerweg 6 +
93047 Regensburg +
info@riodelamiel.eu

=== Anschrift des Seminarhauses
Rio de la Miel, xxx, Province of Malaga,  Spain.

++++
<div id="map"></div>
++++

=== So findet ihr uns mit dem Auto

++++
<div id="route"></div>
++++

=== Postaddresse
Apartado de Correos 504, E18690 Almuñecar, Spain.

=== Busse von und nach Nerja

Hier ist die offizielle Seite mit den Busverbindungen von und nach Nerja:

http://www.nerjatoday.com/nerja/bus-timetables/

=== E-mail:
info@riodelamiel.eu

=== Telefon

[cols="3"]
|===

|*Deutschland*
|
|+49 177 343 2483

|*Spanien*
|
|+34 644 888 098

|*Fax*
|
|+49 1805 006534 2114
|===
