---
key: impressum
layout: pageminimal
---
== Angebote

=== Das Seminarhaus

Das Seminarhaus _Rio de la Miel_ liegt am Rande eines Naturschutzgebietes in der Nähe von Nerja in der Provinz Malaga.
_Rio de la Miel_ wird ausschliesslich als Yogaseminarhaus geführt und bietet seinen Gästen einen ganzheitlichen Aufenthalt
mit täglich 2 geführten Meditationen, 2 Yogastunden und zwei veganen Mahlzeiten (Brunch und Abendessen).

Auf dem gesamten Gelände von _Rio de la Miel_ gilt absolutes Rauch- und Alkoholverbot. Alle Gäste erkennen mit ihrer
Reservierung für die Dauer ihres Aufenthaltes diese Grundregel an.

==== Yogaferien

Yogaferien in _Rio de la Miel_ können jederzeit in beliebiger Länge gebucht werden. Den Gästen der Yogaferien stehen
alle Meditationen und Yogastunden offen. Die Teilnahme ist nicht verpflichtend, jedoch im Sinne einer gemeinsamen
Erfahrung wäre die Teilnahme an einer Meditation und einer Yogastunde am tag wünschenswert.

==== Kurse

Regelmäßig werden in _Rio de la Miel_ Yoga- und Meditationskurse mit erfahrenen Yogalehrern angeboten. Die Unterbringung
der Kursteilnehmer erfolgt ebenfalls in _Rio de la Miel_. Sofern kein gesondertes Kursprogramm angeboten wird, stehen
den Kursteilnehmern allle Veranstaltungen des normalen Tagesprogrammes in _Rio de la Miel_ offen.
Ja nach Kurs finden zusätzliche Vortäge oder Workshops statt.

==== Karmayoga

Je nach Verfügbarkeit können Yoga-Interessierte gegen Kost, Logis, Meditation und eine Yogastunde täglich in
_Rio de la Miel_ helfen. Die Form der Hilfe richtet sich nach aktuellem Bedarf und Fähigkeiten. Die Mitarbeit pro Tag
beträgt ca. 4 Stunden.

Wähend des Seminarbetriebes werden wir in erster Linie Hilfe bei der Reinigung, in der Küche und bei der Gästebetreuung
benötigen. In ruhigeren Phasen planen wir den weiteren Ausbau von _Rio de la Miel_.

=== Reservierung und Buchung

. Die Reservierung des Aufenthalts erfolgt direkt über die Webseite www.riodelamiel.eu, durch die Webseiten unserer
Kooperationspartner, durch eMail oder telefonisch. Eine Reservierung sollte immer unter Angabe eines gewünschten
Aufenthaltszeitraumes bzw. Seminars und einer Zimmerkategorie erfolgen.
. Nach Eingang der Reservierung wird diese von _Rio de la Miel_ per eMail bestätigt. Nach erhalt der
Reservierungsbestätigung ist innerhalb von 5 Tagen eine Anzahlung von 20% des Gesamtpreises zu entrichten, so daß
ausreichend Zeit gegeben ist, um Flüge für die Anreise zu buchen.
. Für einen Karmayogaaufenthalt reicht die schriftliche Bestätigung seitens _Rio de la Miel_ für die Verbindlichkeit aus.
. Wird innerhalb von 5 Arbeitstagen die Anzahlung nicht geleistet, verfällt die Reservierung und muss erneut getätigt  werden.
. 4 Wochen vor Reiseantritt ist die Restzahlung zu entrichten. Sollte die Zahlung nicht rechtzeitg erfolgen, behält sich
_Rio de la Miel_ vor, die reservierten Plätze anderweitig zu vergeben.

=== Stornierungen

. Die Reise kann vor Reiseantritt storniert werden. In diesem Fall erhält der Gast einen Gutschein für einen späteren
Aufenthalt in _Rio de la Miel_ in Höhe der bisher geleisteten Zahlung abzüglich einer Bearbeitungsgebühr
.. bis 4 Wochen vor Reiseantritt 50€
.. bis 1 Tag vor Reiseantritt 100€
. Wird die Reise ohne Angabe von Gründen nicht angetreten, so besteht kein Anspruch auf eine Rückerstattung. Wir
empfehlen den Abschluß einer Reisekostenversicherung, um krankheitsbedingte Reiseausfälle abzudecken.
. Sofern ein Kurs auf Grund mangelnder Anmeldungen nicht durchgeführt werden kann, kann der Gast zwischen einer
kostenfreien Stornierung und einer Umwandlung in einen Yogaaufenthalt wählen. Im Falle der Umwandlung werden eventuell
zuviel gezahlte Kursgebühren zurück erstattet.

---

== Rechtliche Hinweise

=== Haftungsbeschränkung

Die Inhalte des Internetauftritts wurden mit größtmöglicher Sorgfalt und nach bestem Gewissen erstellt. Dennoch übernimmt
der Anbieter dieser Webseite keine Gewähr für die Aktualität, Vollständigkeit und Richtigkeit der bereitgestellten Seiten
und Inhalte.

Als Diensteanbieter ist der Anbieter dieser Webseite gemäß § 7 Abs. 1 TMG für eigene Inhalte und bereitgestellte
Informationen auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich; nach den §§ 8 bis 10 TMG jedoch nicht
verpflichtet, die übermittelten oder gespeicherten fremden Informationen zu überwachen. Eine Entfernung oder Sperrung
dieser Inhalte erfolgt umgehend ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung.
Eine Haftung ist erst ab dem Zeitpunkt der Kenntniserlangung möglich.

=== Externe Links

Die Webseite enthält sog. „externe Links“ (Verlinkungen) zu anderen Webseiten, auf deren Inhalt der Anbieter der
Webseite keinen Einfluss hat. Aus diesem Grund kann der Anbieter für diese Inhalte auch keine Gewähr übernehmen.
Für die Inhalte und Richtigkeit der bereitgestellten Informationen ist der jeweilige Anbieter der verlinkten Webseite
verantwortlich. Zum Zeitpunkt der Verlinkung waren keine Rechtsverstöße erkennbar. Bei Bekanntwerden einer solchen
Rechtsverletzung wird der Link umgehend entfernt.

=== Urheberrecht/Leistungsschutzrecht

Die auf dieser Webseite veröffentlichten Inhalte, Werke und bereitgestellten Informationen unterliegen dem deutschen
Urheberrecht und Leistungsschutzrecht. Jede Art der Vervielfältigung, Bearbeitung, Verbreitung, Einspeicherung und
jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedarf der vorherigen schriftlichen Zustimmung des
jeweiligen Rechteinhabers. Das unerlaubte Kopieren/Speichern der bereitgestellten Informationen auf diesen Webseiten
ist nicht gestattet und strafbar.

=== Datenschutz

Durch den Besuch des Internetauftritts können Informationen (Datum, Uhrzeit, aufgerufene Seite) über den Zugriff auf
dem Server gespeichert werden. Es werden keine personenbezogenenen (z. B. Name, Anschrift oder E-Mail-Adresse) Daten,
gespeichert.

Sofern personenbezogene Daten erhoben werden, erfolgt dies, sofern möglich, nur mit dem vorherigen Einverständnis des
Nutzers der Webseite. Eine Weitergabe der Daten an Dritte findet ohne ausdrückliche Zustimmung des Nutzers nicht statt.

Der Anbieter weist darauf hin, dass die Übertragung von Daten im Internet (z. B. per E-Mail) Sicherheitslücken aufweisen
und ein lückenloser Schutz der Daten vor dem Zugriff Dritter nicht gewährleistet werden kann. Der Anbieter übernimmt
keine Haftung für die durch solche Sicherheitslücken entstandenen Schäden.

Der Verwendung der Kontaktdaten durch Dritte zur gewerblichen Nutzung wird ausdrücklich widersprochen. Es sei denn,
der Anbieter hat zuvor seine schriftliche Einwilligung erteilt. Der Anbieter behält sich rechtliche Schritte für den
Fall der unverlangten Zusendung von Werbeinformationen, z.B. durch Spam-Mails, vor.

---

[cols="3"]
|===
|*Verantwortlich für den Inhalt*
|
|WoQ - Way of Quality GmbH

|*Geschäftsführer*
|
|Andreas Gies

|*eMail*
|
|andreas@wayofquality.de

|*Telefon*
|
|+49 151 23470823

|*Fax*
|
|+49 1805 006534 2114

|*Handelsregister*
|
|AG Regensburg	HRB 14542

|*Ust.-Id.*
|
|DE274771254
|===
