permalink: /posts/:title.html
url: http://www.riodelamiel.eu

owner:
  name: Rio de la Miel
  facebook: riodelamiel
  twitter:
    user: yogariodelamiel
    hashtag: YogaRioDeLaMiel

google_analytics: "UA-51632968-2"

gems:
  - jekyll-asciidoc
  - jekyll-sitemap

versions:
  jquery : "1.11.3"
  bootstrap: "3.3.5"

collections:
  courses:
    output: true
    permalink: /courses/:path.html
  content:
    output: true
    permalink: /pages/:path.html

defaults:
  -
    scope:
      path: ""
    values:
      type: "page"
      share: "true"
      lang: "de"
      layout: "default"
  -
    scope:
      path: "_posts/en"
    values:
      type: "posts"
      lang: "en"
  -
    scope:
      path: "_posts/de"
    values:
      type: "posts"
      lang: "de"
  -
    scope:
      path: "pages/en"
    values:
      lang: "en"
  -
    scope:
      path: "courses"
    values:
      type: "course"
      layout: "course"
  -
    scope:
      path: "courses/en"
    values:
      layout: "course"
      lang: "en"
  -
    scope:
      path: "trainer"
    values:
      type: "trainer"
      layout: "trainer"
  -
    scope:
      path: "trainer/en"
    values:
      lang: "en"

# Enforce the standard ASCIIDOC behavior for Jekyll.
asciidoctor:
  attributes:
    - hardbreaks!

