permalink: /:title.html
url: http://www.riodelamiel.eu

owner:
  name: Rio de la Miel
  facebook: riodelamiel
  twitter:
    user: yogariodelamiel
    hashtag: YogaRioDeLaMiel

google_analytics: "UA-51632968-2"

gems:
  - jekyll-asciidoc
  - jekyll-sitemap

versions:
  jquery : "1.11.3"
  bootstrap: "3.3.5"

banners:
  - img: "Banner1.jpg"
    alt: "Banner1"
  - img: "Banner2.jpg"
    alt: "Banner2"
  - img: "Banner3.jpg"
    alt: "Banner3"

links:
  - link: "/index.html"
    text: "Home"
    key:  "index"
  - link: "/blog.html"
    text: "Blog"
    key:  "blog"
  - link: "/courses.html"
    text: "Kurse"
    key:  "courses"
  - link: "/about.html"
    text: "Über uns"
    key:  "about"
  - link: "/contact.html"
    text: "Kontakt"
    key:  "contact"
  - link: "/impressum.html"
    text: "Impressum"
    key:  "impressum"

collections:
  courses:
    output: true
    permalink: /courses/:path.html
  pages:
    output: true
    permalink: /pages/:path.html

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/de
    values:
      share: true
      lang: de
  -
    scope:
      path: _posts/en
    values:
      share: true
      lang: en
  -
    scope:
      path: _pages/de
    values:
      lang: de
      share: true
  -
    scope:
      path: _pages/en
    values:
      share: true
      lang: en
  -
    scope:
      path: _courses/de
    values:
      layout: course
      lang: de
      share: true
  -
    scope:
      path: _courses/en
    values:
      layout: course
      share: true
      lang: en

# Enforce the standard ASCIIDOC behavior for Jekyll.
asciidoctor:
  attributes:
    - hardbreaks!

