owner:
  name: Rio de la Miel
  facebook: riodelamiel

gems:
  - jekyll-asciidoc

versions:
  jquery : "1.11.3"
  bootstrap: "3.3.5"

banners:
  - img: "Banner1.jpg"
    alt: "Banner1"
  - img: "Banner2.jpg"
    alt: "Banner2"
  - img: "Banner3.jpg"
    alt: "Banner3"
  - img: "Banner4.jpg"
    alt: "Banner4"

links:
  - link: "/index.html"
    text: "Home"
    key:  "index"
  - link: "/about.html"
    text: "Über uns"
    key:  "about"
  - link: "/contact.html"
    text: "Kontakt"
    key:  "contact"
  - link: "/impressum.html"
    text: "Impressum"
    key:  "impressum"

# Enforce the standard ASCIIDOC behavior for Jekyll.
asciidoctor:
  attributes:
    - hardbreaks!