permalink: /:year/:month/:day/:title.html
url: http://www.riodelamiel.eu

owner:
  name: Rio de la Miel
  facebook: riodelamiel
  twitter:
    user: yogariodelamiel
    hashtag: YogaRioDeLaMiel

gems:
  - jekyll-asciidoc

versions:
  jquery : "1.11.3"
  bootstrap: "3.3.5"

banners:
  - img: "Banner1.jpg"
    alt: "Banner1"
  - img: "Banner2.jpg"
    alt: "Banner2"
  - img: "Banner3.jpg"
    alt: "Banner3"

links:
  - link: "/index.html"
    text: "Home"
    key:  "index"
  - link: "/blog.html"
    text: "Blog"
    key:  "blog"
  - link: "/about.html"
    text: "Über uns"
    key:  "about"
  - link: "/contact.html"
    text: "Kontakt"
    key:  "contact"
  - link: "/impressum.html"
    text: "Impressum"
    key:  "impressum"

# Enforce the standard ASCIIDOC behavior for Jekyll.
asciidoctor:
  attributes:
    - hardbreaks!

