---
key: agb
layout: pageminimal
---

== Angebote

=== Das Seminarhaus

Das Seminarhaus _Rio de la Miel_ liegt am Rande eines Naturschutzgebietes in der Nähe von Nerja in der Provinz Malaga.
_Rio de la Miel_ wird ausschliesslich als Yogaseminarhaus geführt und bietet seinen Gästen einen ganzheitlichen
Aufenthalt mit täglich 2 geführten Meditationen, 2 Yogastunden und zwei veganen Mahlzeiten (Brunch und Abendessen).

Auf dem gesamten Gelände von _Rio de la Miel_ gilt absolutes Rauch- und Alkoholverbot. Alle Gäste erkennen mit ihrer
Reservierung für die Dauer ihres Aufenthaltes diese Grundregel an.

=== Yogaferien

Yogaferien in _Rio de la Miel_ können jederzeit in beliebiger Länge gebucht werden. Den Gästen der Yogaferien stehen
alle Meditationen und Yogastunden offen. Die Teilnahme ist nicht verpflichtend, jedoch im Sinne einer gemeinsamen
Erfahrung wäre die Teilnahme an einer Meditation und einer Yogastunde am tag wünschenswert.

=== Kurse

Regelmäßig werden in _Rio de la Miel_ Yoga- und Meditationskurse mit erfahrenen Yogalehrern angeboten. Die Unterbringung
der Kursteilnehmer erfolgt ebenfalls in _Rio de la Miel_. Sofern kein gesondertes Kursprogramm angeboten wird, stehen den
Kursteilnehmern allle Veranstaltungen des normalen Tagesprogrammes in _Rio de la Miel_ offen. Ja nach Kurs finden
zusätzliche Vortäge oder Workshops statt.

=== Karmayoga

Je nach Verfügbarkeit können Yoga-Interessierte gegen Kost, Logis, Meditation und eine Yogastunde täglich in _Rio de la Miel_
helfen. Die Form der Hilfe richtet sich nach aktuellem Bedarf und Fähigkeiten. Wähend des Seminarbetriebes werden wir
in erster Linie Hilfe bei der Reinigung, in der Küche und bei der Gästebetreuung benötigen. In ruhigeren Phasen planen
wir den weiteren Ausbau von _Rio de la Miel_.

== Reservierung und Buchung

. Die Reservierung des Aufenthalts erfolgt direkt über die Webseite www.riodelamiel.eu, durch die Webseiten unserer
Kooperationspartner, durch eMail oder telefonisch. Eine Reservierung sollte immer unter Angabe eines gewünschten
Aufenthaltszeitraumes bzw. Seminars und einer Zimmerkategorie erfolgen.
. Nach Eingang der Reservierung wird diese von _Rio de la Miel_ per eMail bestätigt. Nach erhalt der Reservierungsbestätigung
ist innerhalb von 5 Tagen eine Anzahlung von 20% des Gesamtpreises zu entrichten, so daß ausreichend Zeit gegeben
ist, um Flüge für die Anreise zu buchen.
. Für einen Karmayogaaufenthalt reicht die schriftliche Bestätigung seitens _Rio de la Miel_ für die Verbindlichkeit
aus.
. Wird innerhalb von 5 Arbeitstagen die Anzahlung nicht geleistet, verfällt die Reservierung und muss erneut getätigt
 werden.
. 4 Wochen vor Reiseantritt ist die Restzahlung zu entrichten. Sollte die Zahlung nicht rechtzeitg erfolgen, behält sich
_Rio de la Miel_ vor, die reservierten Plätze anderweitig zu vergeben.

== Stornierungen

. Die Reise kann bis 4 Wochen vor Reiseantritt kostenfrei storniert werden. Bei einer Stornierung zu einem späteren
Zeitpunkt erhält der Gast einen Gutschein für einen späteren Aufenthalt in _Rio de la Miel_ im Wert der geleisteten
Anzahlung abzüglich einer Bearbeitungsgebühr von 50€.y
. Sofern ein Kurs auf Grund mangelnder Anmeldungen nicht durchgeführt werden kann, kann der Gast zwischen einer
kostenfreien Stornierung und einer Umwandlung in einen Zogaaufenthalt wählen.
. Im Falle jeder kostenfreien Stornierung wird die geleistete Anzahlung innerhalb von 5 Arbeitstagen nach Eingang der
Stornierung zurück erstattet.