---
key: contact
---
=== Contact us
For any questions you might have regarding your seminar in Rio de la Miel do not hesitate to contact us by eMail. We
will answer as quick as we possibly can.

We also help you to the best of our knowledge organising your travel and inform you about additional points of interest
close to Rio de la Miel.

Do not hesitate to contact us - we are glad to help.

=== Organiser
WoQ - Way of Quality GmbH +
Stahlzwingerweg 6 +
93047 Regensburg +
info@riodelamiel.eu

=== Address of the seminar house
Rio de la Miel, xxx, Province of Malaga,  Spain.

++++
<div id="map"></div>
++++

=== How to get to us by car

++++
<div id="route"></div>
++++

=== Postal address
Karin & Andreas Gies +
Apartado 1082 +
E18697 La Herradura +
Spain

=== Busses to and from Nerja

This is the official web site with all the buses to and from Nerja:

http://www.nerjatoday.com/nerja/bus-timetables/

=== eMail:
info@riodelamiel.eu

=== Telephone:

[cols="3"]
|===

|*Germany*
|
|+49 177 343 2483

|*Spain*
|
|+34 644 888 098

|*Telefax*
|
|+49 1805 006534 2114
|===
