---
key: impressum
---

== English version

== Angebote

=== The Seminar House

The seminar house _Rio de la Miel_ is is at the edge of the nature reserve called Sierra de Tejeda. The next bigger
village is Nerja in the province of Malaga. _Rio de la Miel_ exclusively offers Yoga vacations and seminars
and offers a holistic experience to its guests. The daily Yoga practice includes 2 meditations, 2 Yoga lessons and
2 vegan meals (brunch and diner).

_Rio de la Miel_ is completely smoke- and alcohol free. All guests accept this basic rule for their stay at _Rio de la
Miel_ when they submit their reservation.

==== Yoga vacation

Yoga vacations in _Rio de la Miel_ can be booked without limitation with a minimum stay of 3 days.

All Yoga vacation guests can participate in all meditations and open Yoga lessons. The participation is voluntary, but
every guest should keep in mind that the energy of _Rio de la Miel_ increases with every single person participating in
a Yoga lesson, meditation or satsan.

==== Kurse

On a regular basis there will be Yoga courses in _Rio de la Miel_ conducted by experienced Yoga teachers. All course
participants will also stay in _Rio de la Miel_ and can participate in all Yoga classes and meditations unless there
is a course specific class or presentation.

==== Karmayoga

We will need help to run _Rio de la Miel_ and invite people who interested to help us to live with us for a while. We
offer free food, shelter, meditation and one Yoga lesson a day. We would expect you to help us 4-6 hours a day in return.

Once we have opened for seminars we will mainly need help in the kitchen, with cleaning and in the garden. In quiet phases
we are planning to make _Rio de la Miel_ even more beautiful.

If you interested to come and help, please get in contact with us and let us know for when and for how long you are
interested to come.

=== Reservations

. foo
. Die Reservierung des Aufenthalts erfolgt direkt über die Webseite www.riodelamiel.eu, durch die Webseiten unserer
Kooperationspartner, durch eMail oder telefonisch. Eine Reservierung sollte immer unter Angabe eines gewünschten
Aufenthaltszeitraumes bzw. Seminars und einer Zimmerkategorie erfolgen.
. Nach Eingang der Reservierung wird diese von _Rio de la Miel_ per eMail bestätigt. Nach erhalt der
Reservierungsbestätigung ist innerhalb von 5 Tagen eine Anzahlung von 20% des Gesamtpreises zu entrichten, so daß
ausreichend Zeit gegeben ist, um Flüge für die Anreise zu buchen.
. Für einen Karmayogaaufenthalt reicht die schriftliche Bestätigung seitens _Rio de la Miel_ für die Verbindlichkeit aus.
. Wird innerhalb von 5 Arbeitstagen die Anzahlung nicht geleistet, verfällt die Reservierung und muss erneut getätigt  werden.
. 4 Wochen vor Reiseantritt ist die Restzahlung zu entrichten. Sollte die Zahlung nicht rechtzeitg erfolgen, behält sich
_Rio de la Miel_ vor, die reservierten Plätze anderweitig zu vergeben.

=== Cancellations

. The stay at _Rio de la Miel_ can be cancelled until 1 day before the stay. With a cancellation the guest will receive
a voucher for a later stay in _Rio de la Miel_ equivalent to the amount paid to date less a cancellation fee of
.. 50€ if the vacation should have started in more than 4 weeks
.. 100€ if the vacation should have started in less than 4 weeks.
. If the guest does not arrive to a booked vacation without notice, the paid amount up to date is forfeited. We recommend
to consider a travel insurance to cover for cases of illnes etc.
. In case a course has to be cancelled due to lack of interest, the guest can choose between a cancellation free of charge
and Yoga vacations at _Rio de la Miel_. In any of these cases any overpaid amount will be transferred to the guests bank
account or the credit card used for pyayments.

---

== Rechtliche Hinweise

=== Haftungsbeschränkung

Die Inhalte des Internetauftritts wurden mit größtmöglicher Sorgfalt und nach bestem Gewissen erstellt. Dennoch übernimmt
der Anbieter dieser Webseite keine Gewähr für die Aktualität, Vollständigkeit und Richtigkeit der bereitgestellten Seiten
und Inhalte.

Als Diensteanbieter ist der Anbieter dieser Webseite gemäß § 7 Abs. 1 TMG für eigene Inhalte und bereitgestellte
Informationen auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich; nach den §§ 8 bis 10 TMG jedoch nicht
verpflichtet, die übermittelten oder gespeicherten fremden Informationen zu überwachen. Eine Entfernung oder Sperrung
dieser Inhalte erfolgt umgehend ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung.
Eine Haftung ist erst ab dem Zeitpunkt der Kenntniserlangung möglich.

=== Externe Links

Die Webseite enthält sog. „externe Links“ (Verlinkungen) zu anderen Webseiten, auf deren Inhalt der Anbieter der
Webseite keinen Einfluss hat. Aus diesem Grund kann der Anbieter für diese Inhalte auch keine Gewähr übernehmen.
Für die Inhalte und Richtigkeit der bereitgestellten Informationen ist der jeweilige Anbieter der verlinkten Webseite
verantwortlich. Zum Zeitpunkt der Verlinkung waren keine Rechtsverstöße erkennbar. Bei Bekanntwerden einer solchen
Rechtsverletzung wird der Link umgehend entfernt.

=== Urheberrecht/Leistungsschutzrecht

Die auf dieser Webseite veröffentlichten Inhalte, Werke und bereitgestellten Informationen unterliegen dem deutschen
Urheberrecht und Leistungsschutzrecht. Jede Art der Vervielfältigung, Bearbeitung, Verbreitung, Einspeicherung und
jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedarf der vorherigen schriftlichen Zustimmung des
jeweiligen Rechteinhabers. Das unerlaubte Kopieren/Speichern der bereitgestellten Informationen auf diesen Webseiten
ist nicht gestattet und strafbar.

=== Datenschutz

Durch den Besuch des Internetauftritts können Informationen (Datum, Uhrzeit, aufgerufene Seite) über den Zugriff auf
dem Server gespeichert werden. Es werden keine personenbezogenenen (z. B. Name, Anschrift oder E-Mail-Adresse) Daten,
gespeichert.

Sofern personenbezogene Daten erhoben werden, erfolgt dies, sofern möglich, nur mit dem vorherigen Einverständnis des
Nutzers der Webseite. Eine Weitergabe der Daten an Dritte findet ohne ausdrückliche Zustimmung des Nutzers nicht statt.

Der Anbieter weist darauf hin, dass die Übertragung von Daten im Internet (z. B. per E-Mail) Sicherheitslücken aufweisen
und ein lückenloser Schutz der Daten vor dem Zugriff Dritter nicht gewährleistet werden kann. Der Anbieter übernimmt
keine Haftung für die durch solche Sicherheitslücken entstandenen Schäden.

Der Verwendung der Kontaktdaten durch Dritte zur gewerblichen Nutzung wird ausdrücklich widersprochen. Es sei denn,
der Anbieter hat zuvor seine schriftliche Einwilligung erteilt. Der Anbieter behält sich rechtliche Schritte für den
Fall der unverlangten Zusendung von Werbeinformationen, z.B. durch Spam-Mails, vor.

---

[cols="3"]
|===
|*Responsible for the content*
|
|WoQ - Way of Quality GmbH

|*General Manager*
|
|Andreas Gies

|*eMail*
|
|andreas@wayofquality.de

|*Telefon*
|
|+49 151 23470823

|*Telefax*
|
|+49 1805 006534 2114

|*Registered*
|
|AG Regensburg	HRB 14542

|*VAT-Id.*
|
|DE274771254
|===
