---
key: impressum
---

== Rio de la Miel

=== The Seminar House

The seminar house _Rio de la Miel_ is is at the edge of the nature reserve called Sierra de Tejeda. The next bigger
village is Nerja in the province of Malaga. _Rio de la Miel_ exclusively offers Yoga vacations and seminars
and offers a holistic experience to its guests. The daily Yoga practice includes 2 meditations, 2 Yoga lessons and
2 vegan meals (brunch and diner).

_Rio de la Miel_ is completely smoke- and alcohol free. All guests accept this basic rule for their stay at _Rio de la
Miel_ when they submit their reservation.

==== Yoga vacation

Yoga vacations in _Rio de la Miel_ can be booked without limitation with a minimum stay of 3 days.

All Yoga vacation guests can participate in all meditations and open Yoga lessons. The participation is voluntary, but
every guest should keep in mind that the energy of _Rio de la Miel_ increases with every single person participating in
a Yoga lesson, meditation or satsan.

==== Courses

On a regular basis there will be Yoga courses in _Rio de la Miel_ conducted by experienced Yoga teachers. All course
participants will also stay in _Rio de la Miel_ and can participate in all Yoga classes and meditations unless there
is a course specific class or presentation.

==== Karma Yoga

We will need help to run _Rio de la Miel_ and invite people who interested to help us to live with us for a while. We
offer free food, shelter, meditation and one Yoga lesson a day. We would expect you to help us 4-6 hours a day in return.

Once we have opened for seminars we will mainly need help in the kitchen, with cleaning and in the garden. In quiet phases
we are planning to make _Rio de la Miel_ even more beautiful.

If you are interested to come and help, please get in contact with us and let us know for when and for how long you are
interested to come.

=== Reservations

. Reservations are accepted via the web site www.riodelamiel.eu, eMail to reservations@riodelamiel.eu, phone and fax.
All reservations should specify the start and the end date of the stay and any courses the guest wants to participate in.
. All reservations will be answered by _Rio de la Miel_ with either a confirmation or a deinal in case the course is
already sold out.
. In case a reservation is confirmed it will be guaranteed for 7 days. After 7 days a deposit of 20% of the total
price must be made to make the guarantee permanent. This should give enough time to arrange flights for the visit.
. For Karma Yogis a confirmation from _Rio de la Miel_ is sufficient for a permanent guarantee. We would ask Karmayogis
to let us know as early as possible if they can't come as planned.
. If the deposit is not made within 7 days, the reservation is forfeited and must be redone.
. 4 weeks before the seminar or vacation the rest of the total price must be paid. If the payment is not made in time,
_Rio de la Miel_ has the right to offer the reserved slots again.

=== Cancellations

. The stay at _Rio de la Miel_ can be cancelled until 1 day before the stay. With a cancellation the guest will receive
a voucher for a later stay in _Rio de la Miel_ equivalent to the amount paid to date less a cancellation fee of
.. 50€ if the vacation should have started in more than 4 weeks
.. 100€ if the vacation should have started in less than 4 weeks.
. If the guest does not arrive to a booked vacation without notice, the paid amount up to date is forfeited. We recommend
to consider a travel insurance to cover for cases of illnes etc.
. In case a course has to be cancelled due to lack of interest, the guest can choose between a cancellation free of charge
and Yoga vacations at _Rio de la Miel_. In any of these cases any overpaid amount will be transferred to the guests bank
account or the credit card used for pyayments.

---

== Legal

The contents of our pages were created with great care. For the correctness, completeness and actuality we can not
take any responsibility. As a service provider we are responsible according to 1 MDStV and 1 TDG for own contents
on these pages under the general laws. However, we are not obligated to monitor the transmitted or stored foreign
information or to investigate circumstances that indicate illegal activity. Obligations to remove or block the use
of information under the general laws remain unaffected. However, liability is only possible from the date of
knowledge of a specific infringement. Upon notification of such violations, we will remove the content immediately.

Our offer contains links to external websites over which we have no control. Therefore we can not accept any
responsibility for their content. The respective provider or operator of the pages is always responsible for
the content of linked pages. The linked sites were checked at the time of linking for possible violations of law.
Illegal contents were not recognizable. A permanent control of the linked pages is unreasonable without concrete
evidence of a violation. Upon notification of violations, we will remove such links immediately.

The operators of these pages aim to observe or to use their own or license-free works the copyrights of others.
The contents and works on these pages created by the site operator are subject to German copyright law. Third party
contributions are marked as such. Duplication, processing, distribution and any kind of exploitation outside the
limits of copyright require the written consent of the respective author or creator.

=== Data protection

Bei using this web site we may gather information regarding the web site traffic such as location, date and time of the
access, browser used etc.

We will not gather nor store personal information without the consent of the user. Using the contact form implies
consent to store the data of the form for internal processes. _Rio de la Miel_ will only use the data for its own
purposes and will not pass the data to any 3rd party.

The contact data of _Rio de la Miel_ may not be used for marketing purposes unless we have explicitly agrred to do so.

---

[cols="3"]
|===
|*Responsible for the content*
|
|WoQ - Way of Quality GmbH

|*General Manager*
|
|Andreas Gies

|*eMail*
|
|andreas@wayofquality.de

|*Telefon*
|
|+49 151 23470823

|*Telefax*
|
|+49 1805 006534 2114

|*Registered*
|
|AG Regensburg	HRB 14542

|*VAT-Id.*
|
|DE274771254
|===
