---
title:   Helfen in Rio de la Miel
date:    2015-08-27
summary: Von Oktober 2015 bis März 2016 werden wir ein neues Yoga Seminarhaus in Rio de la Miel bei Nerja in der Provinz Malaga eröffnen und laden interessierte Helfer ein, uns gegen freie Kost und Logis ein Stück auf diesem Weg zu begleiten.
---

== In eigener Sache

Hallo Ihr Lieben!

*Jetzt ist es so weit:* Im Oktober werden wir unser Seminarhaus in Andalusien beziehen. Allerdings ist es bis zur
Eröffnung Ostern 2016 noch ein langer Weg.

Wer Lust hat, diesen mit uns zu gehen - und wenn es nur ein kleines Stück ist - ist herzlich eingeladen!

=== Wo ist es ?

Das Seminar Haus befindet sich am Rio de la Miel (Der Honigfluss) am Rand des Naturschutzgebietes Sierra Tejada. Der nächtstgelegene Ort ist Nerja in der Provinz Malaga am Mittelmeer.

=== Was bieten wir ?

* Freie Kost und Logis.
* Wir haben kleine gemütliche Zimmer mit eigenem Bad und Platz für bis zu 10 Helfer.
* Das Essen ist vegan – Die Lebensmittel beziehen wir vorwiegend von regionalen Anbietern.
* Wer will kann mit uns Yoga praktizieren und/oder meditieren (Anfängern zeigen wir gerne die ersten Schritte ins Yoga).

Das Haus ist in einem  guten Zustand und sofort bewohnbar - also keine Bauruine. Um es aber als Seminarhaus betreiben zu können, müssen noch einige Dinge verbessert werden.

=== Wir Brauchen:

* Menschen die das vegane kochen lieben:
* die Lust haben mit uns vegane Gerichte zu kreieren, die auch nicht-Veganern schmecken und _massentauglich_ sind.
Wir haben hoffentlich bis dahin eine große Küche. Unser Pizza/Brotbackofen wartet schon auf Arbeit
* Menschen die gerne handwerklich oder gestalterisch arbeiten: Der Pool, Tische und Stühle müssten gestrichen werden. 
* Wir wollen mit viel Phantasie kleine Oasen der Ruhe schaffen. Unsere Quelle wartet darauf, einen schöneren Rahmen zu bekommen. 
* Der Meditationsraum soll einrichten werden. 
* Sonstige Arbeiten, von denen wir jetzt noch nichts wissen ... 
* Menschen, die Lust am Wandern haben: Die Wanderwege rund um das Seminarhaus sollen erkundet, gekennzeichnet und
idealerweise auch in eine Karte eingetragen werden.
* Menschen die Pflanzen und Bäume lieben: Wir haben ein großes Grundstück mit Avocado-,Mandel-, Feigen-, Wahlnuss-,
Pflaumenbäumen und viel Platz für weitere Pflanzen.
* Wir möchten gerne einen Kräutergaten samt einer Kräuterspirale anlegen. Außerdem gibt es Platz für den ein oder anderen Blumengarten.
* Menschen die Bits und Bytes lieben: Obwohl Andreas Informatiker ist, brauchen wir doch Hilfe bei der Gestaltung der Internetseite.
* Menschen, die Lust haben eine kurze oder lange Zeit bei uns zu wohnen - auch ohne irgend welche besonderen Fähigkeiten.

=== Wichtig zu wissen:

* Wir sind absolute Nichtraucher! Das heisst, im Seminarhaus und auf dem gesamten Gelände ist absolutes Rauchverbot
(schon allein wegen der Brandgefahr)
* Das Seminarhaus ist Fleisch- und Alkoholfrei. In der Stadt könnt ihr natürlich essen und trinken was ihr wollt.

*Uns ist egal*

* welchen Glauben ihr habt
* woher ihr kommt
* ob ihr Geld habt
* was ihr esst 
* was ihr seid

*Wir erwarten, dass jeder Gast von uns dies genauso praktiziert.*

Wir haben 5 Hunde, die frei auf dem Grundstück laufen. Solltet ihr Angst vor Hunden haben - Ängste sind dazu da,
überwunden zu werden :D.

=== Sonstiges

* Flüge bitte erst nach Absprache mit uns buchen!
* Arbeitszeit - Es gibt keine Arbeitszeit.
** Wer Lust hat zu helfen - hilft.
** Wer gerne den ganzen Tag meditiert – sucht sich den richtigen Platz.
** Wer die Sonne genießen will - nimmt sich einen Liegestuhl (passt auf, sie könnten noch nass vom Streichen sein ....).
** Wer dem Meer zuhören möchte  - braucht ein Auto oder ist gut zu Fuß ;)
** Oder Ihr besucht die Alhambra, Granada, die Höhlen von Nerja ...
* Wie lange könnt Ihr bleiben:So lange ihr wollt – von einem Tag bis Ende März 2016.
* *Familien:* Familien mit Kindern sind natürlich willkommen.

*Wichtig zu wissen ist, dass wir noch im Umbau sind. Es wird immer irgendwo Farbe offen rumstehen, Werkzeug herum liegen, Abhänge oder Gruben könnten nicht gesichert sein. Der Pool ist nicht eingezäunt.*

*Hunde:* Wir haben 5 Hunde auf 1 oder 2 mehr kommt es nicht an. Nur mit anderen Hunden, Menschen und Kindern müssen sie sich gut verstehen.

=== Wie kommt ihr zu uns:

Die Anreise erfolgt auf eigene Kosten und in eigener Regie - Fragen zur Anreise könnt ihr uns gerne stellen. Der nächste
Flughafen ist Malaga von dort geht jede halbe Stunde ein Bus nach Nerja. Den Fahrplan und die Kosten stellen wir noch
online. Falls ihr mit dem Taxi vom Flughafen kommen wollt, sagt uns Bescheid - wir bekommen bessere Preise.

In Nerja können wir euch gerne abholen - mit uns unbedingt die Zeit absprechen. Ihr könnt euch aber auch gerne ein Auto
am Flughafen mieten (im Herbst gibt es super Angebote). Dann schicken wir euch eine genaue Wegbeschreibung.

*Mit dem Auto von Deutschland* - wer längerbleiben will - braucht ihr ca. 24h reine Fahrzeit (ca. 2500km). Hinzu kommen
noch ca. 200€ Autobahngebühren für eine Strecke.